# On every push this script is executed
on: [workflow_dispatch]
name: Build and push obisidan-zola to pages branch
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        # In the spot where it says v0.1.3.1-alpha, update that to the latest release tag on a new release
        uses: VilianasDev/vilianasdev.github.io@0.0.1
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
